spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/fraud_detection}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:934625}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=true
app.ml-service.enabled=${ML_SERVICE_ENABLED:true}
app.ml-service.url=${ML_SERVICE_URL:http://localhost:8000}
logging.level.com.bank.frauddetection=DEBUG
logging.level.org.springframework.security=INFO
